import { listType } from '@/components/my-travel/types';

export const reviews: listType[] = [
  {
    nickname: '김돌멍',
    review_id: 1,
    title: '여행 일정 추천합니다.',
    rating: 4.5,
    like_count: 120,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    nickname: '박여행',
    review_id: 2,
    title: '힐링되는 여행지였습니다!',
    rating: 4.8,
    like_count: 340,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    nickname: '최모험',
    review_id: 3,
    title: '모험을 좋아하는 사람들에게 추천!',
    rating: 4.2,
    like_count: 87,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    nickname: '최모험',
    review_id: 4,
    title: '모험을 좋아하는 사람들에게 추천!',
    rating: 4.2,
    like_count: 87,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    nickname: '최모험',
    review_id: 5,
    title: '모험을 좋아하는 사람들에게 추천!',
    rating: 4.2,
    like_count: 87,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    nickname: '최모험',
    review_id: 6,
    title: '모험을 좋아하는 사람들에게 추천!',
    rating: 4.2,
    like_count: 87,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    nickname: '최모험',
    review_id: 7,
    title: '모험을 좋아하는 사람들에게 추천!',
    rating: 4.2,
    like_count: 87,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    nickname: '최모험',
    review_id: 8,
    title: '모험을 좋아하는 사람들에게 추천!',
    rating: 4.2,
    like_count: 87,
    created_at: new Date(),
    updated_at: new Date(),
  },
];
